# Importação da Bibliotecas

In [365]:
import numpy as np

from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
#import para o percentual segundo documentação do sklearn
from sklearn.metrics import accuracy_score

import warnings 
warnings.filterwarnings('ignore')

# Dados

Definição dos animais, sem a indicação das `features`, apenas indormando quais são os animais.

In [6]:
animais = np.array([
    [1, 0, 1, 1, 0, 1, 1, 'Poodle'],
    [0, 0, 0, 1, 1, 0, 0, 'Poodle'],
    [1, 1, 1, 1, 1, 1, 0, 'Poodle'],
    [0, 0, 0, 0, 1, 1, 0, 'Poodle'],
    [1, 1, 1, 0, 1, 0, 0, 'Poodle'],
    [0, 1, 1, 1, 0, 1, 0, 'Doberman'],
    [0, 1, 1, 1, 0, 0, 1, 'Doberman'],
    [0, 1, 1, 1, 1, 1, 1, 'Doberman'],
    [0, 0, 1, 0, 0, 0, 1, 'Doberman'],
    [1, 1, 0, 1, 1, 0, 0, 'Doberman'],
    [1, 1, 0, 0, 1, 0, 1, 'Pit Bull'],
    [1, 0, 0, 1, 0, 0, 1, 'Pit Bull'],
    [0, 0, 0, 0, 1, 1, 1, 'Pit Bull'],
    [0, 0, 0, 1, 1, 0, 0, 'Pit Bull'],
    [1, 0, 1, 0, 1, 1, 0, 'Pit Bull'],
    [0, 0, 0, 1, 1, 1, 0, 'Fila'],
    [1, 1, 1, 0, 1, 1, 0, 'Fila'],
    [0, 1, 1, 1, 1, 1, 0, 'Fila'],
    [1, 1, 0, 0, 1, 1, 1, 'Fila'],
    [0, 1, 1, 1, 0, 0, 1, 'Fila']
])

# Conjunto de testes

In [345]:
dados_teste = [
  [0, 1, 1, 1, 1, 1, 0], # Fila
  [0, 1, 1, 1, 1, 1, 1], # Doberman
  [0, 0, 0, 0, 1, 1, 1], # Pit Bull
  [0, 0, 0, 0, 1, 1, 0], # Poodle
  [1, 0, 1, 1, 0, 1, 1]  # Poodle
]       

# Criação dos Modelos com a SKLearn

In [327]:
mm = MultinomialNB()
tree = DecisionTreeClassifier(max_depth=10)
knn = KNeighborsClassifier(n_neighbors=5)
logreg = LogisticRegression()
gnb = GaussianNB()

# Atividade
___

## 1. Separação dos Dados

In [355]:
# Separar os dados em "X" para características e "y" para animais
X = animais[::, :7].astype(int)
y = animais[:,7]

In [356]:
print(X)

[[1 0 1 1 0 1 1]
 [0 0 0 1 1 0 0]
 [1 1 1 1 1 1 0]
 [0 0 0 0 1 1 0]
 [1 1 1 0 1 0 0]
 [0 1 1 1 0 1 0]
 [0 1 1 1 0 0 1]
 [0 1 1 1 1 1 1]
 [0 0 1 0 0 0 1]
 [1 1 0 1 1 0 0]
 [1 1 0 0 1 0 1]
 [1 0 0 1 0 0 1]
 [0 0 0 0 1 1 1]
 [0 0 0 1 1 0 0]
 [1 0 1 0 1 1 0]
 [0 0 0 1 1 1 0]
 [1 1 1 0 1 1 0]
 [0 1 1 1 1 1 0]
 [1 1 0 0 1 1 1]
 [0 1 1 1 0 0 1]]


In [357]:
print(y)

['Poodle' 'Poodle' 'Poodle' 'Poodle' 'Poodle' 'Doberman' 'Doberman'
 'Doberman' 'Doberman' 'Doberman' 'Pit Bull' 'Pit Bull' 'Pit Bull'
 'Pit Bull' 'Pit Bull' 'Fila' 'Fila' 'Fila' 'Fila' 'Fila']


## 2. Treinando os modelos

In [359]:
mmT = mm.fit(X, y)
treeT = tree.fit(X, y)
knnT = knn.fit(X, y)
logregT = logreg.fit(X, y)
gnbT = gnb.fit(X, y)

## 3. Realizando as predições

**Respostas esperadas**:
* Fila, Doberman, Pit Bull, Poodle, Poodle

In [377]:
print(f'MultinomialNB: {mmT.predict(dados_teste)}\n')
print(f'Decision Tree: {treeT.predict(dados_teste)}\n')
print(f'Logistic Regression: {logregT.predict(dados_teste)}\n')
print(f'Knn: {knnT.predict(dados_teste)}\n')
print(f'Gaussian: {gnbT.predict(dados_teste)}\n')

MultinomialNB: ['Fila' 'Doberman' 'Pit Bull' 'Fila' 'Pit Bull']

Decision Tree: ['Fila' 'Doberman' 'Pit Bull' 'Poodle' 'Poodle']

Logistic Regression: ['Fila' 'Fila' 'Pit Bull' 'Pit Bull' 'Poodle']

Knn: ['Doberman' 'Doberman' 'Fila' 'Pit Bull' 'Doberman']

Gaussian: ['Fila' 'Fila' 'Pit Bull' 'Pit Bull' 'Doberman']



## 4. Qual modelo teve o maior desempenho, considerando a sequência de acertos?

a) MultinomialNB

b) Decision Tree

c) Logistic Regression

d) KNN

e) Gaussian

In [ ]:
# Resposta: b, Decision Tree

## 5. Mostra o percentual de acerto de **cada modelo**.

In [427]:
# criando lista padrão
y_true = ['Fila', 'Doberman', 'Pit Bull', 'Poodle', 'Poodle']

#recolhendo percentuais
percent_mmt = accuracy_score(y_true, mmT.predict(dados_teste))*100
percent_tree = accuracy_score(y_true, treeT.predict(dados_teste))*100
percent_logreg = accuracy_score(y_true, logregT.predict(dados_teste))*100
percent_knn = accuracy_score(y_true, knnT.predict(dados_teste))*100
percent_gnb = accuracy_score(y_true, gnbT.predict(dados_teste))*100

#printando percentuais
print(f'MultinomialNB: {percent_mmt}%\n')
print(f'Decision Tree: {percent_tree}%\n')
print(f'Logistic Regression: {percent_logreg}%\n')
print(f'Knn: {percent_knn}%\n')
print(f'Gaussian: {percent_gnb}%\n')


MultinomialNB: 60.0%

Decision Tree: 100.0%

Logistic Regression: 60.0%

Knn: 20.0%

Gaussian: 40.0%



___

# Para fins de experimentos e aprendizado (não será considerada como questão)

Altere os dados de `discreto` para `contínuo` nas `features` abaixo e execute os modelos com os novos dados.

Verifique se há melhora ou piora em cada um deles.



In [ ]:
animais = np.array([
    [1, 0, 1, 1, 0, 1, 1, 'Poodle'],
    [0, 0, 0, 1, 1, 0, 0, 'Poodle'],
    [1, 1, 1, 1, 1, 1, 0, 'Poodle'],
    [0, 0, 0, 0, 1, 1, 0, 'Poodle'],
    [1, 1, 1, 0, 1, 0, 0, 'Poodle'],
    [0, 1, 1, 1, 0, 1, 0, 'Doberman'],
    [0, 1, 1, 1, 0, 0, 1, 'Doberman'],
    [0, 1, 1, 1, 1, 1, 1, 'Doberman'],
    [0, 0, 1, 0, 0, 0, 1, 'Doberman'],
    [1, 1, 0, 1, 1, 0, 0, 'Doberman'],
    [1, 1, 0, 0, 1, 0, 1, 'Pit Bull'],
    [1, 0, 0, 1, 0, 0, 1, 'Pit Bull'],
    [0, 0, 0, 0, 1, 1, 1, 'Pit Bull'],
    [0, 0, 0, 1, 1, 0, 0, 'Pit Bull'],
    [1, 0, 1, 0, 1, 1, 0, 'Pit Bull'],
    [0, 0, 0, 1, 1, 1, 0, 'Fila'],
    [1, 1, 1, 0, 1, 1, 0, 'Fila'],
    [0, 1, 1, 1, 1, 1, 0, 'Fila'],
    [1, 1, 0, 0, 1, 1, 1, 'Fila'],
    [0, 1, 1, 1, 0, 0, 1, 'Fila']
])

dados_teste = [
  [0, 1, 1, 1, 1, 1, 0], # Fila
  [0, 1, 1, 1, 1, 1, 1], # Doberman
  [0, 0, 0, 0, 1, 1, 1], # Pit Bull
  [0, 0, 0, 0, 1, 1, 0], # Poodle
  [1, 0, 1, 1, 0, 1, 1]  # Poodle
]